// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjmGHaNo4OlLL428LmXSCUi9K8lePqTVY',
    appId: '1:439101888198:android:95f116921b4eeebaf9e9c7',
    messagingSenderId: '439101888198',
    projectId: 'twitter-df1e6',
    storageBucket: 'twitter-df1e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgvYOG7i9X3Pc4lWbAepM-j_tpU3J8oo',
    appId: '1:439101888198:ios:cb06fcd2477ee98cf9e9c7',
    messagingSenderId: '439101888198',
    projectId: 'twitter-df1e6',
    storageBucket: 'twitter-df1e6.appspot.com',
    androidClientId: '439101888198-ijkd07ae94eomdd17n9rs72074cu0ua8.apps.googleusercontent.com',
    iosClientId: '439101888198-ue53ivirmb3a3dfde55ns0fifehifl2j.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

}